clock:
  n2: 3125
  out_dividers:
  - 1
  - 3840
  - 3840
  - 6
  - 12
  - 6
  - 12
  output_clocks:
    AD9081_ref_clk:
      divider: 1
      rate: 3000000000.0
    adc_fpga_link_out_clk:
      divider: 12
      rate: 250000000.0
    adc_fpga_ref_clk:
      divider: 6
      rate: 500000000.0
    adc_sysref:
      divider: 3840
      rate: 781250.0
    dac_fpga_link_out_clk:
      divider: 12
      rate: 250000000.0
    dac_fpga_ref_clk:
      divider: 6
      rate: 500000000.0
    dac_sysref:
      divider: 3840
      rate: 781250.0
  r2: 128
  vco: 3000000000.0
  vcxo: 122880000.0
  vcxo_doubler: 1
converter:
  clocking_option: integrated_pll
  pll_config:
    d: 1
    m_vco: 8
    n_vco: 2
    r: 4
    serdes_pll_div: 1
datapath_adc:
  cddc:
    decimations:
    - 4
    - 4
    - 4
    - 4
    enabled:
    - true
    - true
    - true
    - true
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
  fddc:
    decimations:
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    enabled:
    - true
    - true
    - false
    - false
    - true
    - true
    - false
    - false
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    source:
    - 1
    - 1
    - 2
    - 2
    - 3
    - 3
    - 4
    - 4
datapath_dac:
  cduc:
    enabled:
    - true
    - true
    - true
    - true
    interpolation: 6
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
    sources:
    - - 1
    - - 1
    - - 3
    - - 3
  fduc:
    enabled:
    - true
    - true
    - true
    - true
    interpolation: 8
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
fpga_adc:
  d: 1
  m: 1
  n1: 5
  n2: 2
  out_clk_select: XCVR_REFCLK_DIV2
  separate_device_clock_required: 1
  sys_clk_select: XCVR_CPLL
  transport_samples_per_clock: 1
  type: cpll
  vco: 5000000000.0
fpga_dac:
  band: 0
  d: 1
  m: 1
  n: 20
  out_clk_select: XCVR_REFCLK_DIV2
  qty4_full_rate_enabled: 1
  separate_device_clock_required: 1
  sys_clk_select: XCVR_QPLL0
  transport_samples_per_clock: 1
  type: qpll
  vco: 10000000000.0
jesd_adc:
  CS: 0
  F: 4
  HD: 0
  K: 32
  L: 4
  M: 8
  Np: 16
  S: 1
  bit_clock: 10000000000.0
  converter_clock: 4000000000
  jesd_class: jesd204b
  jesd_mode: '10'
  multiframe_clock: 7812500.0
  sample_clock: 250000000
jesd_dac:
  CS: 0
  F: 4
  HD: 0
  K: 32
  L: 4
  M: 8
  Np: 16
  S: 1
  bit_clock: 10000000000.0
  converter_clock: 12000000000
  jesd_class: jesd204b
  jesd_mode: '9'
  multiframe_clock: 7812500.0
  sample_clock: 250000000
