adc_bit_clock: 5720000000.0
clock:
  n2: 17875
  out_dividers:
  - 10
  - 2560
  - 2560
  - 20
  - 1772
  - 10
  - 320
  output_clocks:
    AD9081_ref_clk:
      divider: 10
      rate: 286000000.0
    adc_fpga_link_out_clk:
      divider: 1772
      rate: 1613995.4853273137
    adc_fpga_ref_clk:
      divider: 20
      rate: 143000000.0
    adc_sysref:
      divider: 2560
      rate: 1117187.5
    dac_fpga_link_out_clk:
      divider: 320
      rate: 8937500.0
    dac_fpga_ref_clk:
      divider: 10
      rate: 286000000.0
    dac_sysref:
      divider: 2560
      rate: 1117187.5
  r2: 768
  vco: 2860000000.0
  vcxo: 122880000.0
  vcxo_doubler: 1
converter:
  clocking_option: integrated_pll
  pll_config:
    d: 2
    m_vco: 8
    n_vco: 9
    r: 3
    serdes_pll_div: 1
dac_bit_clock: 5720000000.0
datapath_adc:
  cddc:
    decimations:
    - 2
    - 2
    - 2
    - 2
    enabled:
    - true
    - true
    - true
    - true
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
  fddc:
    decimations:
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    enabled:
    - true
    - true
    - false
    - false
    - true
    - true
    - false
    - false
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    source:
    - 1
    - 1
    - 2
    - 2
    - 3
    - 3
    - 4
    - 4
datapath_dac:
  cduc:
    enabled:
    - true
    - true
    - true
    - true
    interpolation: 4
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
    sources:
    - - 1
    - - 1
    - - 3
    - - 3
  fduc:
    enabled:
    - true
    - true
    - true
    - true
    interpolation: 6
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
fpga_adc:
  band: 1
  d: 2
  m: 1
  n: 80
  out_clk_select: XCVR_PROGDIV_CLK
  progdiv: 40.0
  qty4_full_rate_enabled: 0
  separate_device_clock_required: 0
  sys_clk_select: XCVR_QPLL0
  transport_samples_per_clock: 1
  type: qpll
  vco: 11440000000.0
fpga_dac:
  band: 1
  d: 2
  m: 4
  n: 160
  out_clk_select: XCVR_REFCLK_DIV2
  qty4_full_rate_enabled: 0
  separate_device_clock_required: 1
  sys_clk_select: XCVR_QPLL0
  transport_samples_per_clock: 16
  type: qpll
  vco: 11440000000.0
jesd_adc:
  CS: 0
  F: 4
  HD: 0
  K: 32
  L: 4
  M: 8
  Np: 16
  S: 1
  bit_clock: 5720000000.0
  converter_clock: 1716000000
  jesd_class: jesd204b
  jesd_mode: '10'
  multiframe_clock: 4468750.0
  sample_clock: 143000000
jesd_dac:
  CS: 0
  F: 4
  HD: 0
  K: 32
  L: 4
  M: 8
  Np: 16
  S: 1
  bit_clock: 5720000000.0
  converter_clock: 3432000000
  jesd_class: jesd204b
  jesd_mode: '9'
  multiframe_clock: 4468750.0
  sample_clock: 143000000
