ADC_freq: 2816000000
DAC_freq: 5632000000
cddc: 2
cduc: 2
cfg:
  adc_bit_clock: 14080000000.0
  clock:
    n2: 275
    out_dividers:
    - 2
    - 2048
    - 2048
    - 8
    - 876
    - 4
    - 64
    output_clocks:
      AD9081_ref_clk:
        divider: 2
        rate: 1408000000.0
      adc_fpga_link_out_clk:
        divider: 876
        rate: 3214611.872146119
      adc_fpga_ref_clk:
        divider: 8
        rate: 352000000.0
      adc_sysref:
        divider: 2048
        rate: 1375000.0
      dac_fpga_link_out_clk:
        divider: 64
        rate: 44000000.0
      dac_fpga_ref_clk:
        divider: 4
        rate: 704000000.0
      dac_sysref:
        divider: 2048
        rate: 1375000.0
    r2: 12
    vco: 2816000000.0
    vcxo: 122880000.0
    vcxo_doubler: 1
  converter:
    clocking_option: integrated_pll
    pll_config:
      d: 2
      m_vco: 8
      n_vco: 3
      r: 3
      serdes_pll_div: 1
  dac_bit_clock: 14080000000.0
  datapath_adc:
    cddc:
      decimations:
      - 2
      - 2
      - 2
      - 2
      enabled:
      - true
      - true
      - true
      - true
      nco_frequencies:
      - 0
      - 0
      - 0
      - 0
      nco_phases:
      - 0
      - 0
      - 0
      - 0
    fddc:
      decimations:
      - 4
      - 4
      - 4
      - 4
      - 4
      - 4
      - 4
      - 4
      enabled:
      - true
      - true
      - false
      - false
      - true
      - true
      - false
      - false
      nco_frequencies:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      nco_phases:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      source:
      - 1
      - 1
      - 2
      - 2
      - 3
      - 3
      - 4
      - 4
  datapath_dac:
    cduc:
      enabled:
      - true
      - true
      - true
      - true
      interpolation: 2
      nco_frequencies:
      - 0
      - 0
      - 0
      - 0
      nco_phases:
      - 0
      - 0
      - 0
      - 0
      sources:
      - - 1
      - - 1
      - - 3
      - - 3
    fduc:
      enabled:
      - true
      - true
      - true
      - true
      interpolation: 8
      nco_frequencies:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      nco_phases:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
  fpga_adc:
    band: 1
    d: 1
    m: 1
    n: 40
    out_clk_select: XCVR_PROGDIV_CLK
    progdiv: 40.0
    qty4_full_rate_enabled: 0
    separate_device_clock_required: 0
    sys_clk_select: XCVR_QPLL0
    transport_samples_per_clock: 16
    type: qpll
    vco: 14080000000.0
  fpga_dac:
    band: 1
    d: 1
    m: 4
    n: 80
    out_clk_select: XCVR_REFCLK_DIV2
    qty4_full_rate_enabled: 0
    separate_device_clock_required: 1
    sys_clk_select: XCVR_QPLL0
    transport_samples_per_clock: 8
    type: qpll
    vco: 14080000000.0
  jesd_adc:
    CS: 0
    F: 4
    HD: 0
    K: 32
    L: 4
    M: 8
    Np: 16
    S: 1
    bit_clock: 14080000000.0
    converter_clock: 2816000000
    jesd_class: jesd204b
    jesd_mode: '10'
    multiframe_clock: 11000000.0
    sample_clock: 352000000
  jesd_dac:
    CS: 0
    F: 4
    HD: 0
    K: 32
    L: 4
    M: 8
    Np: 16
    S: 1
    bit_clock: 14080000000.0
    converter_clock: 5632000000
    jesd_class: jesd204b
    jesd_mode: '9'
    multiframe_clock: 11000000.0
    sample_clock: 352000000
fddc: 4
fduc: 8
sample_rate: 352000000.0
