ADC_freq: 2004000000
DAC_freq: 4008000000
cddc: 2
cduc: 4
cfg:
  adc_bit_clock: 6680000000.0
  clock:
    n2: 4175
    out_dividers:
    - 20
    - 2048
    - 2048
    - 16
    - 3442
    - 8
    - 128
    output_clocks:
      AD9081_ref_clk:
        divider: 20
        rate: 133600000.0
      adc_fpga_link_out_clk:
        divider: 3442
        rate: 776292.8529924463
      adc_fpga_ref_clk:
        divider: 16
        rate: 167000000.0
      adc_sysref:
        divider: 2048
        rate: 1304687.5
      dac_fpga_link_out_clk:
        divider: 128
        rate: 20875000.0
      dac_fpga_ref_clk:
        divider: 8
        rate: 334000000.0
      dac_sysref:
        divider: 2048
        rate: 1304687.5
    r2: 192
    vco: 2672000000.0
    vcxo: 122880000.0
    vcxo_doubler: 1
  converter:
    clocking_option: integrated_pll
    pll_config:
      d: 2
      m_vco: 8
      n_vco: 15
      r: 2
      serdes_pll_div: 1
  dac_bit_clock: 6680000000.0
  datapath_adc:
    cddc:
      decimations:
      - 2
      - 2
      - 2
      - 2
      enabled:
      - true
      - true
      - true
      - true
      nco_frequencies:
      - 0
      - 0
      - 0
      - 0
      nco_phases:
      - 0
      - 0
      - 0
      - 0
    fddc:
      decimations:
      - 6
      - 6
      - 6
      - 6
      - 6
      - 6
      - 6
      - 6
      enabled:
      - true
      - true
      - false
      - false
      - true
      - true
      - false
      - false
      nco_frequencies:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      nco_phases:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      source:
      - 1
      - 1
      - 2
      - 2
      - 3
      - 3
      - 4
      - 4
  datapath_dac:
    cduc:
      enabled:
      - true
      - true
      - true
      - true
      interpolation: 4
      nco_frequencies:
      - 0
      - 0
      - 0
      - 0
      nco_phases:
      - 0
      - 0
      - 0
      - 0
      sources:
      - - 1
      - - 1
      - - 3
      - - 3
    fduc:
      enabled:
      - true
      - true
      - true
      - true
      interpolation: 6
      nco_frequencies:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      nco_phases:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
  fpga_adc:
    band: 1
    d: 2
    m: 1
    n: 80
    out_clk_select: XCVR_PROGDIV_CLK
    progdiv: 40.0
    qty4_full_rate_enabled: 0
    separate_device_clock_required: 0
    sys_clk_select: XCVR_QPLL0
    transport_samples_per_clock: 4
    type: qpll
    vco: 13360000000.0
  fpga_dac:
    band: 0
    d: 2
    m: 3
    n: 120
    out_clk_select: XCVR_REFCLK_DIV2
    qty4_full_rate_enabled: 1
    separate_device_clock_required: 1
    sys_clk_select: XCVR_QPLL0
    transport_samples_per_clock: 8
    type: qpll
    vco: 13360000000.0
  jesd_adc:
    CS: 0
    F: 4
    HD: 0
    K: 32
    L: 4
    M: 8
    Np: 16
    S: 1
    bit_clock: 6680000000.0
    converter_clock: 2004000000
    jesd_class: jesd204b
    jesd_mode: '10'
    multiframe_clock: 5218750.0
    sample_clock: 167000000
  jesd_dac:
    CS: 0
    F: 4
    HD: 0
    K: 32
    L: 4
    M: 8
    Np: 16
    S: 1
    bit_clock: 6680000000.0
    converter_clock: 4008000000
    jesd_class: jesd204b
    jesd_mode: '9'
    multiframe_clock: 5218750.0
    sample_clock: 167000000
fddc: 6
fduc: 6
sample_rate: 167000000.0
