adc_bit_clock: 7680000000.0
clock:
  n2: 25
  out_dividers:
  - 10
  - 2048
  - 2048
  - 16
  - 2446
  - 8
  - 256
  output_clocks:
    AD9081_ref_clk:
      divider: 10
      rate: 307200000.0
    adc_fpga_link_out_clk:
      divider: 2446
      rate: 1255928.0457890434
    adc_fpga_ref_clk:
      divider: 16
      rate: 192000000.0
    adc_sysref:
      divider: 2048
      rate: 1500000.0
    dac_fpga_link_out_clk:
      divider: 256
      rate: 12000000.0
    dac_fpga_ref_clk:
      divider: 8
      rate: 384000000.0
    dac_sysref:
      divider: 2048
      rate: 1500000.0
  r2: 1
  vco: 3072000000.0
  vcxo: 122880000.0
  vcxo_doubler: 1
converter:
  clocking_option: integrated_pll
  pll_config:
    d: 3
    m_vco: 8
    n_vco: 15
    r: 4
    serdes_pll_div: 1
dac_bit_clock: 7680000000.0
datapath_adc:
  cddc:
    decimations:
    - 2
    - 2
    - 2
    - 2
    enabled:
    - true
    - true
    - true
    - true
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
  fddc:
    decimations:
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    enabled:
    - true
    - true
    - false
    - false
    - true
    - true
    - false
    - false
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    source:
    - 1
    - 1
    - 2
    - 2
    - 3
    - 3
    - 4
    - 4
datapath_dac:
  cduc:
    enabled:
    - true
    - true
    - true
    - true
    interpolation: 2
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
    sources:
    - - 1
    - - 1
    - - 3
    - - 3
  fduc:
    enabled:
    - true
    - true
    - true
    - true
    interpolation: 8
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
fpga_adc:
  band: 0
  d: 2
  m: 2
  n: 160
  out_clk_select: XCVR_PROGDIV_CLK
  progdiv: 40.0
  qty4_full_rate_enabled: 1
  separate_device_clock_required: 0
  sys_clk_select: XCVR_QPLL0
  transport_samples_per_clock: 8
  type: qpll
  vco: 15360000000.0
fpga_dac:
  band: 0
  d: 2
  m: 4
  n: 160
  out_clk_select: XCVR_REFCLK_DIV2
  qty4_full_rate_enabled: 1
  separate_device_clock_required: 1
  sys_clk_select: XCVR_QPLL0
  transport_samples_per_clock: 16
  type: qpll
  vco: 15360000000.0
jesd_adc:
  CS: 0
  F: 4
  HD: 0
  K: 32
  L: 4
  M: 8
  Np: 16
  S: 1
  bit_clock: 7680000000.0
  converter_clock: 1536000000
  jesd_class: jesd204b
  jesd_mode: '10'
  multiframe_clock: 6000000.0
  sample_clock: 192000000
jesd_dac:
  CS: 0
  F: 4
  HD: 0
  K: 32
  L: 4
  M: 8
  Np: 16
  S: 1
  bit_clock: 7680000000.0
  converter_clock: 3072000000
  jesd_class: jesd204b
  jesd_mode: '9'
  multiframe_clock: 6000000.0
  sample_clock: 192000000
