ADC_freq: 2040000000
DAC_freq: 4080000000
cddc: 2
cduc: 4
cfg:
  adc_bit_clock: 6800000000.0
  clock:
    n2: 2125
    out_dividers:
    - 5
    - 2048
    - 2048
    - 16
    - 120
    - 8
    - 16
    output_clocks:
      AD9081_ref_clk:
        divider: 5
        rate: 544000000.0
      adc_fpga_link_out_clk:
        divider: 120
        rate: 22666666.666666668
      adc_fpga_ref_clk:
        divider: 16
        rate: 170000000.0
      adc_sysref:
        divider: 2048
        rate: 1328125.0
      dac_fpga_link_out_clk:
        divider: 16
        rate: 170000000.0
      dac_fpga_ref_clk:
        divider: 8
        rate: 340000000.0
      dac_sysref:
        divider: 2048
        rate: 1328125.0
    r2: 96
    vco: 2720000000.0
    vcxo: 122880000.0
    vcxo_doubler: 1
  converter:
    clocking_option: integrated_pll
    pll_config:
      d: 2
      m_vco: 5
      n_vco: 3
      r: 1
      serdes_pll_div: 1
  dac_bit_clock: 6800000000.0
  datapath_adc:
    cddc:
      decimations:
      - 2
      - 2
      - 2
      - 2
      enabled:
      - true
      - true
      - true
      - true
      nco_frequencies:
      - 0
      - 0
      - 0
      - 0
      nco_phases:
      - 0
      - 0
      - 0
      - 0
    fddc:
      decimations:
      - 6
      - 6
      - 6
      - 6
      - 6
      - 6
      - 6
      - 6
      enabled:
      - true
      - true
      - false
      - false
      - true
      - true
      - false
      - false
      nco_frequencies:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      nco_phases:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      source:
      - 1
      - 1
      - 2
      - 2
      - 3
      - 3
      - 4
      - 4
  datapath_dac:
    cduc:
      enabled:
      - true
      - true
      - true
      - true
      interpolation: 4
      nco_frequencies:
      - 0
      - 0
      - 0
      - 0
      nco_phases:
      - 0
      - 0
      - 0
      - 0
      sources:
      - - 1
      - - 1
      - - 3
      - - 3
    fduc:
      enabled:
      - true
      - true
      - true
      - true
      interpolation: 6
      nco_frequencies:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      nco_phases:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
  fpga_adc:
    band: 0
    d: 2
    m: 1
    n: 80
    out_clk_select: XCVR_PROGDIV_CLK
    progdiv: 40.0
    qty4_full_rate_enabled: 1
    separate_device_clock_required: 0
    sys_clk_select: XCVR_QPLL0
    transport_samples_per_clock: 1
    type: qpll
    vco: 13600000000.0
  fpga_dac:
    band: 0
    d: 2
    m: 1
    n: 40
    out_clk_select: XCVR_REFCLK_DIV2
    qty4_full_rate_enabled: 1
    separate_device_clock_required: 1
    sys_clk_select: XCVR_QPLL0
    transport_samples_per_clock: 1
    type: qpll
    vco: 13600000000.0
  jesd_adc:
    CS: 0
    F: 4
    HD: 0
    K: 32
    L: 4
    M: 8
    Np: 16
    S: 1
    bit_clock: 6800000000.0
    converter_clock: 2040000000
    jesd_class: jesd204b
    jesd_mode: '10'
    multiframe_clock: 5312500.0
    sample_clock: 170000000
  jesd_dac:
    CS: 0
    F: 4
    HD: 0
    K: 32
    L: 4
    M: 8
    Np: 16
    S: 1
    bit_clock: 6800000000.0
    converter_clock: 4080000000
    jesd_class: jesd204b
    jesd_mode: '9'
    multiframe_clock: 5312500.0
    sample_clock: 170000000
fddc: 6
fduc: 6
sample_rate: 170000000.0
