adc_bit_clock: 5160000000.0
clock:
  n2: 3225
  out_dividers:
  - 3
  - 3072
  - 3072
  - 24
  - 2
  - 12
  - 48
  output_clocks:
    AD9081_ref_clk:
      divider: 3
      rate: 1032000000.0
    adc_fpga_link_out_clk:
      divider: 2
      rate: 1548000000.0
    adc_fpga_ref_clk:
      divider: 24
      rate: 129000000.0
    adc_sysref:
      divider: 3072
      rate: 1007812.5
    dac_fpga_link_out_clk:
      divider: 48
      rate: 64500000.0
    dac_fpga_ref_clk:
      divider: 12
      rate: 258000000.0
    dac_sysref:
      divider: 3072
      rate: 1007812.5
  r2: 128
  vco: 3096000000.0
  vcxo: 122880000.0
  vcxo_doubler: 1
converter:
  clocking_option: integrated_pll
  pll_config:
    d: 2
    m_vco: 8
    n_vco: 3
    r: 4
    serdes_pll_div: 1
dac_bit_clock: 5160000000.0
datapath_adc:
  cddc:
    decimations:
    - 2
    - 2
    - 2
    - 2
    enabled:
    - true
    - true
    - true
    - true
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
  fddc:
    decimations:
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    enabled:
    - true
    - true
    - false
    - false
    - true
    - true
    - false
    - false
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    source:
    - 1
    - 1
    - 2
    - 2
    - 3
    - 3
    - 4
    - 4
datapath_dac:
  cduc:
    enabled:
    - true
    - true
    - true
    - true
    interpolation: 4
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
    sources:
    - - 1
    - - 1
    - - 3
    - - 3
  fduc:
    enabled:
    - true
    - true
    - true
    - true
    interpolation: 6
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
fpga_adc:
  band: 1
  d: 2
  m: 2
  n: 160
  out_clk_select: XCVR_PROGDIV_CLK
  progdiv: 40.0
  qty4_full_rate_enabled: 0
  separate_device_clock_required: 0
  sys_clk_select: XCVR_QPLL0
  transport_samples_per_clock: 4
  type: qpll
  vco: 10320000000.0
fpga_dac:
  band: 1
  d: 2
  m: 3
  n: 120
  out_clk_select: XCVR_REFCLK_DIV2
  qty4_full_rate_enabled: 0
  separate_device_clock_required: 1
  sys_clk_select: XCVR_QPLL0
  transport_samples_per_clock: 2
  type: qpll
  vco: 10320000000.0
jesd_adc:
  CS: 0
  F: 4
  HD: 0
  K: 32
  L: 4
  M: 8
  Np: 16
  S: 1
  bit_clock: 5160000000.0
  converter_clock: 1548000000
  jesd_class: jesd204b
  jesd_mode: '10'
  multiframe_clock: 4031250.0
  sample_clock: 129000000
jesd_dac:
  CS: 0
  F: 4
  HD: 0
  K: 32
  L: 4
  M: 8
  Np: 16
  S: 1
  bit_clock: 5160000000.0
  converter_clock: 3096000000
  jesd_class: jesd204b
  jesd_mode: '9'
  multiframe_clock: 4031250.0
  sample_clock: 129000000
