adc_bit_clock: 15400000000.0
clock:
  n2: 9625
  out_dividers:
  - 28
  - 2048
  - 2048
  - 8
  - 102
  - 4
  - 32
  output_clocks:
    AD9081_ref_clk:
      divider: 28
      rate: 110000000.0
    adc_fpga_link_out_clk:
      divider: 102
      rate: 30196078.43137255
    adc_fpga_ref_clk:
      divider: 8
      rate: 385000000.0
    adc_sysref:
      divider: 2048
      rate: 1503906.25
    dac_fpga_link_out_clk:
      divider: 32
      rate: 96250000.0
    dac_fpga_ref_clk:
      divider: 4
      rate: 770000000.0
    dac_sysref:
      divider: 2048
      rate: 1503906.25
  r2: 384
  vco: 3080000000.0
  vcxo: 122880000.0
  vcxo_doubler: 1
converter:
  clocking_option: integrated_pll
  pll_config:
    d: 1
    m_vco: 7
    n_vco: 32
    r: 4
    serdes_pll_div: 1
dac_bit_clock: 15400000000.0
datapath_adc:
  cddc:
    decimations:
    - 2
    - 2
    - 2
    - 2
    enabled:
    - true
    - true
    - true
    - true
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
  fddc:
    decimations:
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    enabled:
    - true
    - true
    - false
    - false
    - true
    - true
    - false
    - false
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    source:
    - 1
    - 1
    - 2
    - 2
    - 3
    - 3
    - 4
    - 4
datapath_dac:
  cduc:
    enabled:
    - true
    - true
    - true
    - true
    interpolation: 2
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
    sources:
    - - 1
    - - 1
    - - 3
    - - 3
  fduc:
    enabled:
    - true
    - true
    - true
    - true
    interpolation: 8
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
fpga_adc:
  band: 1
  d: 1
  m: 3
  n: 120
  out_clk_select: XCVR_PROGDIV_CLK
  progdiv: 40.0
  qty4_full_rate_enabled: 0
  separate_device_clock_required: 0
  sys_clk_select: XCVR_QPLL0
  transport_samples_per_clock: 8
  type: qpll
  vco: 15400000000.0
fpga_dac:
  band: 1
  d: 1
  m: 1
  n: 20
  out_clk_select: XCVR_REFCLK_DIV2
  qty4_full_rate_enabled: 0
  separate_device_clock_required: 1
  sys_clk_select: XCVR_QPLL0
  transport_samples_per_clock: 4
  type: qpll
  vco: 15400000000.0
jesd_adc:
  CS: 0
  F: 4
  HD: 0
  K: 32
  L: 4
  M: 8
  Np: 16
  S: 1
  bit_clock: 15400000000.0
  converter_clock: 3080000000
  jesd_class: jesd204b
  jesd_mode: '10'
  multiframe_clock: 12031250.0
  sample_clock: 385000000
jesd_dac:
  CS: 0
  F: 4
  HD: 0
  K: 32
  L: 4
  M: 8
  Np: 16
  S: 1
  bit_clock: 15400000000.0
  converter_clock: 6160000000
  jesd_class: jesd204b
  jesd_mode: '9'
  multiframe_clock: 12031250.0
  sample_clock: 385000000
