adc_bit_clock: 8040000000.0
clock:
  n2: 5025
  out_dividers:
  - 18
  - 3072
  - 3072
  - 12
  - 2902
  - 6
  - 12
  output_clocks:
    AD9081_ref_clk:
      divider: 18
      rate: 134000000.0
    adc_fpga_link_out_clk:
      divider: 2902
      rate: 831150.9303928325
    adc_fpga_ref_clk:
      divider: 12
      rate: 201000000.0
    adc_sysref:
      divider: 3072
      rate: 785156.25
    dac_fpga_link_out_clk:
      divider: 12
      rate: 201000000.0
    dac_fpga_ref_clk:
      divider: 6
      rate: 402000000.0
    dac_sysref:
      divider: 3072
      rate: 785156.25
  r2: 256
  vco: 2412000000.0
  vcxo: 122880000.0
  vcxo_doubler: 1
converter:
  clocking_option: integrated_pll
  pll_config:
    d: 3
    m_vco: 8
    n_vco: 9
    r: 1
    serdes_pll_div: 1
dac_bit_clock: 8040000000.0
datapath_adc:
  cddc:
    decimations:
    - 2
    - 2
    - 2
    - 2
    enabled:
    - true
    - true
    - true
    - true
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
  fddc:
    decimations:
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    enabled:
    - true
    - true
    - false
    - false
    - true
    - true
    - false
    - false
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    source:
    - 1
    - 1
    - 2
    - 2
    - 3
    - 3
    - 4
    - 4
datapath_dac:
  cduc:
    enabled:
    - true
    - true
    - true
    - true
    interpolation: 2
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
    sources:
    - - 1
    - - 1
    - - 3
    - - 3
  fduc:
    enabled:
    - true
    - true
    - true
    - true
    interpolation: 8
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
fpga_adc:
  band: 1
  d: 2
  m: 1
  n: 80
  out_clk_select: XCVR_PROGDIV_CLK
  progdiv: 40.0
  qty4_full_rate_enabled: 0
  separate_device_clock_required: 0
  sys_clk_select: XCVR_QPLL0
  transport_samples_per_clock: 16
  type: qpll
  vco: 16080000000.0
fpga_dac:
  band: 1
  d: 2
  m: 1
  n: 40
  out_clk_select: XCVR_REFCLK_DIV2
  qty4_full_rate_enabled: 0
  separate_device_clock_required: 1
  sys_clk_select: XCVR_QPLL0
  transport_samples_per_clock: 1
  type: qpll
  vco: 16080000000.0
jesd_adc:
  CS: 0
  F: 4
  HD: 0
  K: 32
  L: 4
  M: 8
  Np: 16
  S: 1
  bit_clock: 8040000000.0
  converter_clock: 1608000000
  jesd_class: jesd204b
  jesd_mode: '10'
  multiframe_clock: 6281250.0
  sample_clock: 201000000
jesd_dac:
  CS: 0
  F: 4
  HD: 0
  K: 32
  L: 4
  M: 8
  Np: 16
  S: 1
  bit_clock: 8040000000.0
  converter_clock: 3216000000
  jesd_class: jesd204b
  jesd_mode: '9'
  multiframe_clock: 6281250.0
  sample_clock: 201000000
