ADC_freq: 2048000000
DAC_freq: 4096000000
cddc: 2
cduc: 2
cfg:
  adc_bit_clock: 10240000000.0
  clock:
    n2: 25
    out_dividers:
    - 2
    - 3072
    - 3072
    - 12
    - 4094
    - 6
    - 192
    output_clocks:
      AD9081_ref_clk:
        divider: 2
        rate: 1536000000.0
      adc_fpga_link_out_clk:
        divider: 4094
        rate: 750366.3898387884
      adc_fpga_ref_clk:
        divider: 12
        rate: 256000000.0
      adc_sysref:
        divider: 3072
        rate: 1000000.0
      dac_fpga_link_out_clk:
        divider: 192
        rate: 16000000.0
      dac_fpga_ref_clk:
        divider: 6
        rate: 512000000.0
      dac_sysref:
        divider: 3072
        rate: 1000000.0
    r2: 1
    vco: 3072000000.0
    vcxo: 122880000.0
    vcxo_doubler: 1
  converter:
    clocking_option: integrated_pll
    pll_config:
      d: 2
      m_vco: 8
      n_vco: 2
      r: 3
      serdes_pll_div: 1
  dac_bit_clock: 10240000000.0
  datapath_adc:
    cddc:
      decimations:
      - 2
      - 2
      - 2
      - 2
      enabled:
      - true
      - true
      - true
      - true
      nco_frequencies:
      - 0
      - 0
      - 0
      - 0
      nco_phases:
      - 0
      - 0
      - 0
      - 0
    fddc:
      decimations:
      - 4
      - 4
      - 4
      - 4
      - 4
      - 4
      - 4
      - 4
      enabled:
      - true
      - true
      - false
      - false
      - true
      - true
      - false
      - false
      nco_frequencies:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      nco_phases:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      source:
      - 1
      - 1
      - 2
      - 2
      - 3
      - 3
      - 4
      - 4
  datapath_dac:
    cduc:
      enabled:
      - true
      - true
      - true
      - true
      interpolation: 2
      nco_frequencies:
      - 0
      - 0
      - 0
      - 0
      nco_phases:
      - 0
      - 0
      - 0
      - 0
      sources:
      - - 1
      - - 1
      - - 3
      - - 3
    fduc:
      enabled:
      - true
      - true
      - true
      - true
      interpolation: 8
      nco_frequencies:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      nco_phases:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
  fpga_adc:
    band: 1
    d: 1
    m: 4
    n: 160
    out_clk_select: XCVR_PROGDIV_CLK
    progdiv: 40.0
    qty4_full_rate_enabled: 0
    separate_device_clock_required: 0
    sys_clk_select: XCVR_QPLL0
    transport_samples_per_clock: 16
    type: qpll
    vco: 10240000000.0
  fpga_dac:
    band: 1
    d: 1
    m: 1
    n: 20
    out_clk_select: XCVR_REFCLK_DIV2
    qty4_full_rate_enabled: 0
    separate_device_clock_required: 1
    sys_clk_select: XCVR_QPLL0
    transport_samples_per_clock: 16
    type: qpll
    vco: 10240000000.0
  jesd_adc:
    CS: 0
    F: 4
    HD: 0
    K: 32
    L: 4
    M: 8
    Np: 16
    S: 1
    bit_clock: 10240000000.0
    converter_clock: 2048000000
    jesd_class: jesd204b
    jesd_mode: '10'
    multiframe_clock: 8000000.0
    sample_clock: 256000000
  jesd_dac:
    CS: 0
    F: 4
    HD: 0
    K: 32
    L: 4
    M: 8
    Np: 16
    S: 1
    bit_clock: 10240000000.0
    converter_clock: 4096000000
    jesd_class: jesd204b
    jesd_mode: '9'
    multiframe_clock: 8000000.0
    sample_clock: 256000000
fddc: 4
fduc: 8
sample_rate: 256000000.0
