adc_bit_clock: 4920000000.0
clock:
  n2: 3075
  out_dividers:
  - 20
  - 3072
  - 3072
  - 24
  - 2542
  - 12
  - 24
  output_clocks:
    AD9081_ref_clk:
      divider: 20
      rate: 147600000.0
    adc_fpga_link_out_clk:
      divider: 2542
      rate: 1161290.322580645
    adc_fpga_ref_clk:
      divider: 24
      rate: 123000000.0
    adc_sysref:
      divider: 3072
      rate: 960937.5
    dac_fpga_link_out_clk:
      divider: 24
      rate: 123000000.0
    dac_fpga_ref_clk:
      divider: 12
      rate: 246000000.0
    dac_sysref:
      divider: 3072
      rate: 960937.5
  r2: 128
  vco: 2952000000.0
  vcxo: 122880000.0
  vcxo_doubler: 1
converter:
  clocking_option: integrated_pll
  pll_config:
    d: 4
    m_vco: 5
    n_vco: 16
    r: 1
    serdes_pll_div: 1
dac_bit_clock: 4920000000.0
datapath_adc:
  cddc:
    decimations:
    - 2
    - 2
    - 2
    - 2
    enabled:
    - true
    - true
    - true
    - true
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
  fddc:
    decimations:
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    enabled:
    - true
    - true
    - false
    - false
    - true
    - true
    - false
    - false
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    source:
    - 1
    - 1
    - 2
    - 2
    - 3
    - 3
    - 4
    - 4
datapath_dac:
  cduc:
    enabled:
    - true
    - true
    - true
    - true
    interpolation: 4
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
    sources:
    - - 1
    - - 1
    - - 3
    - - 3
  fduc:
    enabled:
    - true
    - true
    - true
    - true
    interpolation: 6
    nco_frequencies:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    nco_phases:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
fpga_adc:
  band: 1
  d: 2
  m: 2
  n: 160
  out_clk_select: XCVR_PROGDIV_CLK
  progdiv: 40.0
  qty4_full_rate_enabled: 0
  separate_device_clock_required: 0
  sys_clk_select: XCVR_QPLL0
  transport_samples_per_clock: 8
  type: qpll
  vco: 9840000000.0
fpga_dac:
  band: 0
  d: 2
  m: 4
  n: 160
  out_clk_select: XCVR_REFCLK_DIV2
  qty4_full_rate_enabled: 1
  separate_device_clock_required: 1
  sys_clk_select: XCVR_QPLL0
  transport_samples_per_clock: 1
  type: qpll
  vco: 9840000000.0
jesd_adc:
  CS: 0
  F: 4
  HD: 0
  K: 32
  L: 4
  M: 8
  Np: 16
  S: 1
  bit_clock: 4920000000.0
  converter_clock: 1476000000
  jesd_class: jesd204b
  jesd_mode: '10'
  multiframe_clock: 3843750.0
  sample_clock: 123000000
jesd_dac:
  CS: 0
  F: 4
  HD: 0
  K: 32
  L: 4
  M: 8
  Np: 16
  S: 1
  bit_clock: 4920000000.0
  converter_clock: 2952000000
  jesd_class: jesd204b
  jesd_mode: '9'
  multiframe_clock: 3843750.0
  sample_clock: 123000000
